### ISSUE TITLE
Installation is failing for the Suse 15 - sp4

### ISSUE THREAD

**Issue by manjumj1553** [GoogleCloudPlatform/google-cloud-ops-agents-ansible#103]
Using this role to deploy the google-cloud-ops agent on sles15-sp4 is failing with below error.

But if we try executing the script file in /tmp/<anisble script folder>/add-google-cloud-ops-agent-repo.sh it works without any issue. 

TASK [gcp-ops-agent-install : Add repo and install agent or remove repo and uninstall agent] ***
FAILED - RETRYING: Add repo and install agent or remove repo and uninstall agent (5 retries left).
FAILED - RETRYING: Add repo and install agent or remove repo and uninstall agent (4 retries left).
FAILED - RETRYING: Add repo and install agent or remove repo and uninstall agent (3 retries left).
FAILED - RETRYING: Add repo and install agent or remove repo and uninstall agent (2 retries left).
FAILED - RETRYING: Add repo and install agent or remove repo and uninstall agent (1 retries left).
fatal: [10.5.0.179]: FAILED! => {"attempts": 5, "changed": true, "cmd": ["bash", "add-google-cloud-ops-agent-repo.sh", "--also-install", "--version=latest"], "delta": "0:00:55.060665", "end": "2023-08-14 15:54:30.222948", "msg": "non-zero return code", "rc": 1, "start": "2023-08-14 15:53:35.162283", "stderr": "Repository 'Google Cloud Ops Agent Repository' is invalid.\n[google-cloud-ops-agent|https://packages.cloud.google.com/yum/repos/google-cloud-ops-agent-4-x86_64-all] Valid metadata not found at specified URL\nHistory:\n - [google-cloud-ops-agent|https://packages.cloud.google.com/yum/repos/google-cloud-ops-agent-4-x86_64-all] Repository type can't be determined.\n\nPlease check if the URIs defined for this repository are pointing to a valid repository.\nSkipping repository 'Google Cloud Ops Agent Repository' because of the above error.\nSome of the repositories have not been refreshed because of an error.\nCould not refresh zypper repositories.\nThis is not necessarily a fatal error; proceeding...\nRepository 'Google Cloud Ops Agent Repository' is invalid.\n[google-cloud-ops-agent|https://packages.cloud.google.com/yum/repos/google-cloud-ops-agent-4-x86_64-all] Valid metadata not found at specified URL\nHistory:\n - [google-cloud-ops-agent|https://packages.cloud.google.com/yum/repos/google-cloud-ops-agent-4-x86_64-all] Repository type can't be determined.\n\nPlease check if the URIs defined for this repository are pointing to a valid repository.\nSkipping repository 'Google Cloud Ops Agent Repository' because of the above error.\nCould not refresh the repositories because of errors.\n[2023-08-14T15:54:28+0000] Could not refresh the google-cloud-ops-agent zypper repositories.\nPlease check your network connectivity and make sure you are running a supported\nsles distribution. See https://cloud.google.com/stackdriver/docs/solutions/ops-agent/#supported_operating_systems\nfor a list of supported platforms.\nError building the cache:\n[google-cloud-ops-agent|https://packages.cloud.google.com/yum/repos/google-cloud-ops-agent-4-x86_64-all] Valid metadata not found at specified URL\nHistory:\n - [google-cloud-ops-agent|https://packages.cloud.google.com/yum/repos/google-cloud-ops-agent-4-x86_64-all] Repository type can't be determined.\n\nSome of the repositories have not been refreshed because of an error.\nNo provider of 'google-cloud-ops-agent' found.\n[2023-08-14T15:54:30+0000] google-cloud-ops-agent  installation failed.", "stderr_lines": ["Repository 'Google Cloud Ops Agent Repository' is invalid.", "[google-cloud-ops-agent|https://packages.cloud.google.com/yum/repos/google-cloud-ops-agent-4-x86_64-all] Valid metadata not found at specified URL", "History:", " - [google-cloud-ops-agent|https://packages.cloud.google.com/yum/repos/google-cloud-ops-agent-4-x86_64-all] Repository type can't be determined.", "", "Please check if the URIs defined for this repository are pointing to a valid repository.", "Skipping repository 'Google Cloud Ops Agent Repository' because of the above error.", "Some of the repositories have not been refreshed because of an error.", "Could not refresh zypper repositories.", "This is not necessarily a fatal error; proceeding...", "Repository 'Google Cloud Ops Agent Repository' is invalid.", "[google-cloud-ops-agent|https://packages.cloud.google.com/yum/repos/google-cloud-ops-agent-4-x86_64-all] Valid metadata not found at specified URL", "History:", " - [google-cloud-ops-agent|https://packages.cloud.google.com/yum/repos/google-cloud-ops-agent-4-x86_64-all] Repository type can't be determined.", "", "Please check if the URIs defined for this repository are pointing to a valid repository.", "Skipping repository 'Google Cloud Ops Agent Repository' because of the above error.", "Could not refresh the repositories because of errors.", "[2023-08-14T15:54:28+0000] Could not refresh the google-cloud-ops-agent zypper repositories.", "Please check your network connectivity and make sure you are running a supported", "sles distribution. See https://cloud.google.com/stackdriver/docs/solutions/ops-agent/#supported_operating_systems", "for a list of supported platforms.", "Error building the cache:", "[google-cloud-ops-agent|https://packages.cloud.google.com/yum/repos/google-cloud-ops-agent-4-x86_64-all] Valid metadata not found at specified URL", "History:", " - [google-cloud-ops-agent|https://packages.cloud.google.com/yum/repos/google-cloud-ops-agent-4-x86_64-all] Repository type can't be determined.", "", "Some of the repositories have not been refreshed because of an error.", "No provider of 'google-cloud-ops-agent' found.", "[2023-08-14T15:54:30+0000] google-cloud-ops-agent  installation failed."], "stdout": "Repository 'SLE-Module-Basesystem15-SP4-Pool' is up to date.\nRepository 'SLE-Module-Basesystem15-SP4-Updates' is up to date.\nRepository 'SLE-Module-Containers15-SP4-Pool' is up to date.\nRepository 'SLE-Module-Containers15-SP4-Updates' is up to date.\nRepository 'SLE-Module-Desktop-Applications15-SP4-Pool' is up to date.\nRepository 'SLE-Module-Desktop-Applications15-SP4-Updates' is up to date.\nRepository 'SLE-Module-DevTools15-SP4-Pool' is up to date.\nRepository 'SLE-Module-DevTools15-SP4-Updates' is up to date.\nRepository 'SLE-Module-Public-Cloud15-SP4-Pool' is up to date.\nRepository 'SLE-Module-Public-Cloud15-SP4-Updates' is up to date.\nRepository 'SLE-Module-Python3-15-SP4-Pool' is up to date.\nRepository 'SLE-Module-Python3-15-SP4-Updates' is up to date.\nRepository 'SLE-Module-SAP-Applications15-SP4-Pool' is up to date.\nRepository 'SLE-Module-SAP-Applications15-SP4-Updates' is up to date.\nRepository 'SLE-Product-HA15-SP4-Pool' is up to date.\nRepository 'SLE-Product-HA15-SP4-Updates' is up to date.\nRepository 'SLE-Module-Live-Patching15-SP4-Pool' is up to date.\nRepository 'SLE-Module-Live-Patching15-SP4-Updates' is up to date.\nRepository 'SLE-Product-SLES_SAP15-SP4-Pool' is up to date.\nRepository 'SLE-Product-SLES_SAP15-SP4-Updates' is up to date.\nRepository 'SLE-Module-Server-Applications15-SP4-Pool' is up to date.\nRepository 'SLE-Module-Server-Applications15-SP4-Updates' is up to date.\nRepository 'SLE-Module-Web-Scripting15-SP4-Pool' is up to date.\nRepository 'SLE-Module-Web-Scripting15-SP4-Updates' is up to date.\nRetrieving repository 'Google Cloud Ops Agent Repository' metadata [.error]\nRetrieving repository 'Google Cloud Ops Agent Repository' metadata [.error]\nRefreshing service 'Basesystem_Module_x86_64'.\nRefreshing service 'Containers_Module_x86_64'.\nRefreshing service 'Desktop_Applications_Module_x86_64'.\nRefreshing service 'Development_Tools_Module_x86_64'.\nRefreshing service 'Public_Cloud_Module_x86_64'.\nRefreshing service 'Python_3_Module_x86_64'.\nRefreshing service 'SAP_Applications_Module_x86_64'.\nRefreshing service 'SUSE_Linux_Enterprise_High_Availability_Extension_x86_64'.\nRefreshing service 'SUSE_Linux_Enterprise_Live_Patching_x86_64'.\nRefreshing service 'SUSE_Linux_Enterprise_Server_for_SAP_Applications_x86_64'.\nRefreshing service 'Server_Applications_Module_x86_64'.\nRefreshing service 'Web_and_Scripting_Module_x86_64'.\nWarning: Skipping repository 'Google Cloud Ops Agent Repository' because of the above error.\nLoading repository data...\nReading installed packages...\n'google-cloud-ops-agent' not found in package names. Trying capabilities.", "stdout_lines": ["Repository 'SLE-Module-Basesystem15-SP4-Pool' is up to date.", "Repository 'SLE-Module-Basesystem15-SP4-Updates' is up to date.", "Repository 'SLE-Module-Containers15-SP4-Pool' is up to date.", "Repository 'SLE-Module-Containers15-SP4-Updates' is up to date.", "Repository 'SLE-Module-Desktop-Applications15-SP4-Pool' is up to date.", "Repository 'SLE-Module-Desktop-Applications15-SP4-Updates' is up to date.", "Repository 'SLE-Module-DevTools15-SP4-Pool' is up to date.", "Repository 'SLE-Module-DevTools15-SP4-Updates' is up to date.", "Repository 'SLE-Module-Public-Cloud15-SP4-Pool' is up to date.", "Repository 'SLE-Module-Public-Cloud15-SP4-Updates' is up to date.", "Repository 'SLE-Module-Python3-15-SP4-Pool' is up to date.", "Repository 'SLE-Module-Python3-15-SP4-Updates' is up to date.", "Repository 'SLE-Module-SAP-Applications15-SP4-Pool' is up to date.", "Repository 'SLE-Module-SAP-Applications15-SP4-Updates' is up to date.", "Repository 'SLE-Product-HA15-SP4-Pool' is up to date.", "Repository 'SLE-Product-HA15-SP4-Updates' is up to date.", "Repository 'SLE-Module-Live-Patching15-SP4-Pool' is up to date.", "Repository 'SLE-Module-Live-Patching15-SP4-Updates' is up to date.", "Repository 'SLE-Product-SLES_SAP15-SP4-Pool' is up to date.", "Repository 'SLE-Product-SLES_SAP15-SP4-Updates' is up to date.", "Repository 'SLE-Module-Server-Applications15-SP4-Pool' is up to date.", "Repository 'SLE-Module-Server-Applications15-SP4-Updates' is up to date.", "Repository 'SLE-Module-Web-Scripting15-SP4-Pool' is up to date.", "Repository 'SLE-Module-Web-Scripting15-SP4-Updates' is up to date.", "Retrieving repository 'Google Cloud Ops Agent Repository' metadata [.error]", "Retrieving repository 'Google Cloud Ops Agent Repository' metadata [.error]", "Refreshing service 'Basesystem_Module_x86_64'.", "Refreshing service 'Containers_Module_x86_64'.", "Refreshing service 'Desktop_Applications_Module_x86_64'.", "Refreshing service 'Development_Tools_Module_x86_64'.", "Refreshing service 'Public_Cloud_Module_x86_64'.", "Refreshing service 'Python_3_Module_x86_64'.", "Refreshing service 'SAP_Applications_Module_x86_64'.", "Refreshing service 'SUSE_Linux_Enterprise_High_Availability_Extension_x86_64'.", "Refreshing service 'SUSE_Linux_Enterprise_Live_Patching_x86_64'.", "Refreshing service 'SUSE_Linux_Enterprise_Server_for_SAP_Applications_x86_64'.", "Refreshing service 'Server_Applications_Module_x86_64'.", "Refreshing service 'Web_and_Scripting_Module_x86_64'.", "Warning: Skipping repository 'Google Cloud Ops Agent Repository' because of the above error.", "Loading repository data...", "Reading installed packages...", "'google-cloud-ops-agent' not found in package names. Trying capabilities."]}

**Comment by jeewan-gautam** [comment]
Exactly I am getting similar type of error in RHEL

**Comment by manjumj1553** [comment]
We were trying this on **sles**. Apparently if you co mment below lines, it is working properly. Control flow is not breaking and installation is going through fine.

**Filename:** linux.yml
**Line no:** 28 to 31
**Code changes performed**
  **#**retries: 5
  **#**delay: 10
  **#**until: result.rc == 0
  **#**check_mode: false

**Comment by igorpeshansky** [comment]
This was caused by a minor change to the installation scripts that broke an assumption in our ansible playbooks. We'll look into providing a fix; in the meantime, a workaround is to comment out the setting of `REPO_CODENAME` in `linux.yml`.
