### ISSUE TITLE
stackdriver-extractor is not installing

### ISSUE THREAD

**Issue by noose** [GoogleCloudPlatform/google-cloud-ops-agents-ansible#13]
I found that `stackdriver-extractor` is not installed on my system. Why? Because I set `no install recommends` in the apt.
![screen shot 2016-03-17 at 08 57 41](https://cloud.githubusercontent.com/assets/438968/13839805/56ce1588-ec1e-11e5-8a68-5a01a25caad2.png)
Can you fix that? ;-)

**Comment by noose** [comment]
> Installing "stackdriver-agent" installs "stackdriver-extractor" as a dependency. 
https://github.com/GoogleCloudPlatform/stackdriver-ansible-role/blob/master/vars/main.yml#L37 

It's not dependency - it's recommended package.

OS: Ubuntu 14.04.4 LTS

**Comment by rimey** [comment]
I corrected the comment to say it is a recommended package.

I can pass along feedback to the maintainers of these packages if you wish, but note that the extractor is currently in a kind of limbo after this week's major release of Google Stackdriver. The installation procedure recommended by the documentation actually leaves the extractor disabled. (This Ansible role doesn't yet support that new --write-gcm configuration option.)

**Comment by noose** [comment]
Hi @rimey. Sorry for delay. I forgot about that issue. 
I'm trying to install stackdriver but there is error:
```TASK [rimey.stackdriver : Ensure extractor is running.] ************************
fatal: [base1]: FAILED! => {"changed": false, "failed": true, "msg": "no service or tool found for: stackdriver-extractor"}
```
that's why I'm writting about that `stackdriver-extractor`. Imho - it should be installed in task.

**Comment by rimey** [comment]
Hi. Could you provide a little more context?  Is this on GCE? I assume the `stackdriver-agent` package is installed and the `stackdriver-agent` service is running? Is the `stackdriver-extractor` package installed? Try the following two commands:

```
service stackdriver-agent status
service stackdriver-extractor status
```
