### ISSUE TITLE
Mac OSX lacks realpath

### ISSUE THREAD

**Issue by ronjarrell** [GoogleCloudPlatform/google-cloud-ops-agents-ansible#56]
The gcloud scripts depend on realpath to locate the function library, without it you get 

`+++ dirname /path-to-my-tfdir/modules/agent-policy/scripts/create-update-script.sh
module.admin_agent_policy.module.gcloud-upsert.null_resource.run_command[0] (local-exec): ++ realpath /path-to-my-tfdir/modules/agent-policy/scripts
module.admin_agent_policy.module.gcloud-upsert.null_resource.run_command[0] (local-exec): /path-to-my-tfdir/modules/agent-policy/scripts/create-update-script.sh: line 38: realpath: command not found
module.admin_agent_policy.module.gcloud-upsert.null_resource.run_command[0] (local-exec): + SCRIPT_DIR=
module.admin_agent_policy.module.gcloud-upsert.null_resource.run_command[0] (local-exec): + UTILS_ABS_PATH=/script-utils.sh
module.admin_agent_policy.module.gcloud-upsert.null_resource.run_command[0] (local-exec): + source /script-utils.sh
module.admin_agent_policy.module.gcloud-upsert.null_resource.run_command[0] (local-exec): /path-to-my-tfdir/modules/agent-policy/scripts/create-update-script.sh: line 41: /script-utils.sh: No such file or directory
`

Interestingly, the scripts don't elevate that error up to terraform, which thinks the terraform apply worked just fine, but leaving an empty state file and no actual policies.

A workaround is to use homebrew to install coreutils, which has realpath, but the scripts really should either not depend on it, or catch the lack and the failure to execute.

**Comment by ronjarrell** [comment]
I just realized I accidently opened this on the ansible branch, not the terraform code.

**Comment by sophieyfang** [comment]
> I just realized I accidently opened this on the ansible branch, not the terraform code.

No worries, this is the link for terraform: https://github.com/terraform-google-modules/terraform-google-cloud-operations
