### ISSUE TITLE
failing Validate Operating Systen on rocky linux  operating system

### ISSUE THREAD

**Issue by lorenz307** [GoogleCloudPlatform/google-cloud-ops-agents-ansible#63]
TASK [google_cloud_ops_agents : Validate Operating Systen] ***********************************************************************************************************************************************
fatal: []: FAILED! => {
    "assertion": "ansible_os_family == 'Windows' or ansible_distribution in ['Debian', 'Ubuntu', 'RedHat', 'CentOS', 'Amazon', 'SLES', 'openSUSE', 'SuSE', 'SLES_SAP', 'Windows']\n",

**Comment by rmoriar1** [comment]
Rocky Linux isn't currently supported, but it's in the pipeline.
