### ISSUE TITLE
Restart of Ops Agent fails

### ISSUE THREAD

**Issue by Floble** [GoogleCloudPlatform/google-cloud-ops-agents-ansible#73]
Hi everyone,

executing the role, I experienced the following error:

- Error: When using the Ansible role to setup the Ops Agent, the restart of the service fails, because the service with the name "google-cloud-ops-agent.target" cannot be found.

- Experienced on System: Compute Engine instance running Ubuntu 20.04 LTS (Minimal); Installation of latest version of Ops Agent.

- Solution: Change the value of the variable "ops-agent_service_name" in "vars/main.yml" to "google-cloud-ops-agent".

Best regards,
Flo

**Comment by tpdownes** [comment]
#66 is working to address this though it's been inactive lately. You can downgrade to `version: 1.*.*` in the meantime.
